# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_package_name: conmon
downstream_package_name: conmon

jobs:
  - job: copr_build
    # build in new Copr projects
    # workaround for https://github.com/packit/packit-service/issues/1854
    identifier: rawhide
    # Run on every PR
    trigger: pull_request
    # Disable i386 as it's no longer supported.
    # Disable ppc64le and s390x as they take too long on copr.
    targets:
      - fedora-rawhide-aarch64
      - fedora-rawhide-x86_64
      - fedora-38-aarch64
      - fedora-38-x86_64
      - fedora-37-aarch64
      - fedora-37-x86_64
    actions:
      # Rawhide spec file should also build for the released versions of Fedora.
      post-upstream-clone:
        - "curl -O https://src.fedoraproject.org/rpms/conmon/raw/rawhide/f/conmon.spec"
