---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/conmon.spec
upstream_tag_template: v{version}

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    targets:
      - fedora-all-aarch64
      - fedora-all-x86_64
      - fedora-eln-aarch64
      - fedora-eln-x86_64
      - epel-9-aarch64
      - epel-9-x86_64
      - epel-8-aarch64
      - epel-8-x86_64

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
