# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_package_name: conmon
downstream_package_name: conmon

jobs:
  - job: copr_build
    # Run on every PR
    trigger: pull_request
    # Defaults to x86_64 unless architecture is explicitly specified
    targets:
      - fedora-rawhide-aarch64
      - fedora-rawhide-i386
      - fedora-rawhide-ppc64le
      - fedora-rawhide-s390x
      - fedora-rawhide-x86_64
    actions:
      post-upstream-clone:
        - "curl -O https://src.fedoraproject.org/rpms/conmon/raw/rawhide/f/conmon.spec"

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-37-aarch64
      - fedora-37-i386
      - fedora-37-ppc64le
      - fedora-37-s390x
      - fedora-37-x86_64
    actions:
      post-upstream-clone:
        - "curl -O https://src.fedoraproject.org/rpms/conmon/raw/f37/f/conmon.spec"

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-36-aarch64
      - fedora-36-i386
      - fedora-36-ppc64le
      - fedora-36-s390x
      - fedora-36-x86_64
    actions:
      post-upstream-clone:
        - "curl -O https://src.fedoraproject.org/rpms/conmon/raw/f36/f/conmon.spec"
