#!/usr/bin/env bash
set -euo pipefail

declare -A VERSIONS=(
    # renovate: datasource=github-releases depName=containernetworking/plugins
    ["cni-plugins"]=v1.9.0
    # renovate: datasource=github-releases depName=bats-core/bats-core
    ["bats"]=v1.13.0
    # renovate: datasource=github-releases depName=opencontainers/runc
    ["runc"]=v1.4.0
    # renovate: datasource=github-releases depName=containers/crun
    ["crun"]=1.26
)

main() {
    set -x
    prepare_system

    install_packages
    install_conmon
    install_bats
    install_critools
    install_runc
    install_crun
    install_cni_plugins
    install_testdeps
    setup_etc_subid
}

prepare_system() {
    sudo systemctl stop docker
    sudo ufw disable

    # enable necessary kernel modules
    sudo ip6tables --list >/dev/null

    # enable necessary sysctls
    sudo sysctl -w net.ipv4.conf.all.route_localnet=1
    sudo sysctl -w net.ipv4.ip_forward=1
    # needed for crictl test
    sudo modprobe br_netfilter
    sudo sysctl -w net.bridge.bridge-nf-call-iptables=1
    sudo iptables -t nat -I POSTROUTING -s 127.0.0.0/8 ! -d 127.0.0.0/8 -j MASQUERADE
}

remove_packages() {
    sudo apt-get remove \
        conmon \
        containernetworking-plugins
}

install_packages() {
    . /etc/os-release
    CRIU_REPO="https://download.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_$VERSION_ID"

    curl -fSsL $CRIU_REPO/Release.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/criu.gpg
    echo "deb $CRIU_REPO/ /" | sudo tee /etc/apt/sources.list.d/criu.list

    sudo apt update
    sudo apt install -y \
        autoconf \
        automake \
        conntrack \
        criu \
        jq \
        libaio-dev \
        libapparmor-dev \
        libbtrfs-dev \
        libcap-dev \
        libdevmapper-dev \
        libfuse-dev \
        libgpgme11-dev \
        libglib2.0-dev \
        libnet1-dev \
        libnl-3-dev \
        libprotobuf-c-dev \
        libprotobuf-dev \
        libseccomp-dev \
        libsystemd-dev \
        libtool \
        libudev-dev \
        libyajl-dev \
        podman \
        sed \
        socat \
        uuid-dev
}

install_conmon() {
    sudo make install.bin
    conmon --version
}

install_bats() {
    git clone https://github.com/bats-core/bats-core
    pushd bats-core
    git checkout "${VERSIONS["bats"]}"
    sudo ./install.sh /usr/local
    popd
    rm -rf bats-core
    mkdir -p ~/.parallel
    touch ~/.parallel/will-cite
}

install_critools() {
    URL=https://github.com/kubernetes-sigs/cri-tools

    git clone $URL
    pushd cri-tools
    sudo -E PATH="$PATH" make BINDIR=/usr/bin install
    popd
    sudo rm -rf cri-tools
    sudo critest --version
    sudo crictl --version
}

install_cni_plugins() {
    URL=https://github.com/containernetworking/plugins/releases/download
    TARBALL=cni-plugins-linux-amd64-${VERSIONS["cni-plugins"]}.tgz
    CNI_DIR=/opt/cni/bin
    sudo mkdir -p "$CNI_DIR"
    wget -O "$TARBALL" $URL/"${VERSIONS["cni-plugins"]}"/"$TARBALL"
    sudo tar xf "$TARBALL" -C "$CNI_DIR"
    rm "$TARBALL"
    ls -lah "$CNI_DIR"
}

install_runc() {
    git clone --depth 1 --branch "${VERSIONS["runc"]}" https://github.com/opencontainers/runc
    pushd runc
    make
    sudo install -D -m0755 runc /usr/sbin/runc
    popd
    rm -rf runc

    runc --version
}

install_crun() {
    git clone --depth 1 --branch "${VERSIONS["crun"]}" https://github.com/containers/crun
    pushd crun
    ./autogen.sh
    ./configure
    sudo make -j "$(nproc)" install prefix=/usr
    popd
    sudo rm -rf crun

    crun --version
}

install_testdeps() {
    CLONE_PATH=$(go env GOPATH)/src/github.com/cri-o
    mkdir -p "$CLONE_PATH"
    pushd "$CLONE_PATH"

    URL=https://github.com/cri-o/cri-o
    git clone $URL
    pushd cri-o
    make "$(pwd)"/build/bin/ginkgo
    sudo cp build/bin/ginkgo /usr/bin
    ginkgo version

    sudo mkdir -p /etc/containers/registries.d
    sudo cp test/policy.json /etc/containers
    sudo cp test/redhat_sigstore.yaml /etc/containers/registries.d/registry.access.redhat.com.yaml
    sudo cp test/registries.conf /etc/containers/registries.conf
    popd
    popd
}

setup_etc_subid() {
    echo "containers:200000:65536" | sudo tee -a /etc/subuid
    echo "containers:200000:65536" | sudo tee -a /etc/subgid

}

main "$@"
