name: validate
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
permissions:
  contents: read

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check C code formatting
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format
        make fmt
        git diff --exit-code

  all-done:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
    - run: echo "All jobs completed"
