name: validate
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
permissions:
  contents: read

jobs:

  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Verify Go dependencies
      run: |
        make vendor
        git diff --exit-code

  all-done:
    needs:
      - deps
    runs-on: ubuntu-latest
    steps:
    - run: echo "All jobs completed"
